# Generated by Django 5.0.4 on 2024-04-25 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_item_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_At',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
