# Generated by Django 5.0.4 on 2024-04-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
